import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :chatsec, ChatsecWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Traefik terminates TLS and proxies to this app over plain HTTP, so the
  # scheme must be read from X-Forwarded-Proto (which Traefik sets) rather
  # than the raw connection, or force_ssl would redirect every request in a loop.
  force_ssl: [hsts: true, rewrite_on: [:x_forwarded_proto]]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Chatsec.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
